version: "3.8"
services:
  db:
    image: mysql:5.7
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    restart: always
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./config/db:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xvwa
  web:
    build: .
    restart: always
    volumes:
      - "./:/var/www/html/xvwa/"
    ports:
      - 80:80
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
